# Generated by Django 6.1 on 2026-08-29 06:57

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CinemaTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[django_tenants.postgresql_backend.base._check_schema_name],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was initially created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique public identifier for API lookups and routing.",
                        unique=True,
                        verbose_name="public UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Public commercial name of the cinema (e.g. Westgate Cinema, Rupa's Cinemas).",
                        max_length=255,
                        verbose_name="cinema display name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe slug used for subdomain routing (e.g. 'westgate' -> westgate.africinemas.com).",
                        max_length=63,
                        unique=True,
                        verbose_name="subdomain slug",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Nairobi",
                        help_text="City or municipality where the cinema is located (e.g. Nairobi, Eldoret, Kisumu).",
                        max_length=100,
                        verbose_name="city / town",
                    ),
                ),
                (
                    "physical_address",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Physical address within the mall or building (e.g. 2nd Floor, Wing B).",
                        verbose_name="physical address",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Primary administrative and notification email for cinema management.",
                        max_length=254,
                        verbose_name="operational contact email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer support hotline or WhatsApp number.",
                        max_length=32,
                        verbose_name="support contact phone",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this cinema is active and allowed to accept bookings.",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cinema Tenant",
                "verbose_name_plural": "Cinema Tenants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CinemaPaymentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was initially created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique public identifier for API lookups and routing.",
                        unique=True,
                        verbose_name="public UUID",
                    ),
                ),
                (
                    "gateway_mode",
                    models.CharField(
                        choices=[
                            ("INTASEND_ESCROW", "IntaSend Escrow (10% Platform Commission Split)"),
                            ("DIRECT_DARAJA", "Direct Safaricom Daraja (Paybill / Buy Goods)"),
                        ],
                        default="INTASEND_ESCROW",
                        help_text="Default is IntaSend escrow with 10% platform revenue fee split.",
                        max_length=32,
                        verbose_name="payment gateway mode",
                    ),
                ),
                (
                    "platform_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Platform commission fee percentage deducted per transaction (default 10.00%).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="platform fee percentage",
                    ),
                ),
                (
                    "settlement_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="M-Pesa phone number for automated merchant payout disbursements.",
                        max_length=32,
                        verbose_name="settlement M-Pesa phone",
                    ),
                ),
                (
                    "settlement_bank_account",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bank name, account number, and branch for EFT / RTGS payouts.",
                        max_length=255,
                        verbose_name="settlement bank details",
                    ),
                ),
                (
                    "daraja_shortcode",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Safaricom Daraja Paybill or Buy Goods Till Number.",
                        null=True,
                        verbose_name="Daraja shortcode",
                    ),
                ),
                (
                    "daraja_consumer_key",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Daraja 2.0 OAuth Consumer Key.",
                        verbose_name="Daraja consumer key",
                    ),
                ),
                (
                    "daraja_consumer_secret",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Daraja 2.0 OAuth Consumer Secret.",
                        verbose_name="Daraja consumer secret",
                    ),
                ),
                (
                    "daraja_passkey",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Lipa Na M-Pesa Online STK Push Passkey.",
                        verbose_name="Daraja online passkey",
                    ),
                ),
                (
                    "daraja_till_type",
                    models.CharField(
                        choices=[("PAYBILL", "Paybill"), ("BUY_GOODS", "Buy Goods Till")],
                        default="PAYBILL",
                        help_text="Specify whether the shortcode is a Paybill or Buy Goods Till.",
                        max_length=16,
                        verbose_name="Daraja till type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether payment processing is enabled for this cinema.",
                        verbose_name="is payment active",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_config",
                        to="cinemas.cinematenant",
                        verbose_name="cinema tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cinema Payment Configuration",
                "verbose_name_plural": "Cinema Payment Configurations",
            },
        ),
        migrations.CreateModel(
            name="CinemaDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=253, unique=True)),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was initially created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique public identifier for API lookups and routing.",
                        unique=True,
                        verbose_name="public UUID",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="cinemas.cinematenant",
                        verbose_name="cinema tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cinema Domain",
                "verbose_name_plural": "Cinema Domains",
                "ordering": ["domain"],
            },
        ),
        migrations.CreateModel(
            name="CinemaTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was initially created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique public identifier for API lookups and routing.",
                        unique=True,
                        verbose_name="public UUID",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Public CDN URL for transparent SVG / PNG dark-mode logo.",
                        verbose_name="logo URL",
                    ),
                ),
                (
                    "favicon_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Public URL for browser favicon.",
                        verbose_name="favicon URL",
                    ),
                ),
                (
                    "hero_backdrop_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Default banner backdrop image for cinema homepage.",
                        verbose_name="hero backdrop image URL",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#E50914",
                        help_text="Primary brand accent color (hex e.g. #E50914).",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Must be a valid 6-character hex color code (e.g. #E50914).",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="primary color",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#E5A93B",
                        help_text="Secondary badge/highlight color (hex e.g. #E5A93B).",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Must be a valid 6-character hex color code (e.g. #E50914).",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="secondary color",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#0B0B0E",
                        help_text="Main application background color (hex e.g. #0B0B0E).",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Must be a valid 6-character hex color code (e.g. #E50914).",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="background color",
                    ),
                ),
                (
                    "surface_color",
                    models.CharField(
                        default="#14141A",
                        help_text="Card / container surface color (hex e.g. #14141A).",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Must be a valid 6-character hex color code (e.g. #E50914).",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="surface elevated color",
                    ),
                ),
                (
                    "font_display",
                    models.CharField(
                        default="'Outfit', sans-serif",
                        help_text="Font family for titles and headers.",
                        max_length=100,
                        verbose_name="display typography font",
                    ),
                ),
                (
                    "font_body",
                    models.CharField(
                        default="'Inter', sans-serif",
                        help_text="Font family for body text and paragraphs.",
                        max_length=100,
                        verbose_name="body typography font",
                    ),
                ),
                (
                    "border_radius",
                    models.CharField(
                        default="8px",
                        help_text="Global component border radius (e.g. 8px, 12px).",
                        max_length=16,
                        verbose_name="border radius token",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme",
                        to="cinemas.cinematenant",
                        verbose_name="cinema tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cinema Theme",
                "verbose_name_plural": "Cinema Themes",
            },
        ),
    ]
