# Generated by Django 6.1 on 2026-08-29 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinemas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinematheme",
            name="accent_color",
            field=models.CharField(
                default="#3B82F6",
                help_text="Tertiary accent for badges and status highlights.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be a valid 6-character hex color code (e.g. #E50914).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="accent highlight color",
            ),
        ),
        migrations.AddField(
            model_name="cinematheme",
            name="border_color",
            field=models.CharField(
                default="#2A2A36",
                help_text="Dividers and component borders.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be a valid 6-character hex color code (e.g. #E50914).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="subtle border color",
            ),
        ),
        migrations.AddField(
            model_name="cinematheme",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Whether this theme is active on the live storefront or currently in preview/draft mode.",
                verbose_name="is theme published",
            ),
        ),
        migrations.AddField(
            model_name="cinematheme",
            name="primary_hover",
            field=models.CharField(
                default="#B8121B",
                help_text="Hover state for primary buttons and interactive accents.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be a valid 6-character hex color code (e.g. #E50914).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="primary hover color",
            ),
        ),
        migrations.AddField(
            model_name="cinematheme",
            name="surface_elevated",
            field=models.CharField(
                default="#1E1E26",
                help_text="Elevated modals, dropdowns, and navigation headers.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be a valid 6-character hex color code (e.g. #E50914).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="surface elevated color",
            ),
        ),
        migrations.AddField(
            model_name="cinematheme",
            name="text_muted",
            field=models.CharField(
                default="#9CA3AF",
                help_text="Low-emphasis captions and subtitles.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be a valid 6-character hex color code (e.g. #E50914).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="muted text color",
            ),
        ),
        migrations.AddField(
            model_name="cinematheme",
            name="text_on_primary",
            field=models.CharField(
                default="#FFFFFF",
                help_text="Foreground text on primary buttons (auto-calculated for WCAG contrast).",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be a valid 6-character hex color code (e.g. #E50914).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="text on primary color",
            ),
        ),
        migrations.AddField(
            model_name="cinematheme",
            name="text_primary",
            field=models.CharField(
                default="#FFFFFF",
                help_text="High-emphasis headings and body text.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be a valid 6-character hex color code (e.g. #E50914).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="primary text color",
            ),
        ),
        migrations.AddField(
            model_name="cinematheme",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Monotonically increasing version counter for CDN and browser cache busting.",
                verbose_name="theme version",
            ),
        ),
        migrations.AlterField(
            model_name="cinematheme",
            name="primary_color",
            field=models.CharField(
                default="#E61C24",
                help_text="Primary brand accent color (hex e.g. #E61C24).",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be a valid 6-character hex color code (e.g. #E50914).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="primary color",
            ),
        ),
        migrations.AlterField(
            model_name="cinematheme",
            name="secondary_color",
            field=models.CharField(
                default="#E5A93B",
                help_text="Secondary badge/VIP highlight color (hex e.g. #E5A93B).",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be a valid 6-character hex color code (e.g. #E50914).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="secondary color",
            ),
        ),
        migrations.AlterField(
            model_name="cinematheme",
            name="surface_color",
            field=models.CharField(
                default="#14141A",
                help_text="Card / container surface color (hex e.g. #14141A).",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be a valid 6-character hex color code (e.g. #E50914).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
                verbose_name="surface container color",
            ),
        ),
    ]
