# Generated by Django 6.1 on 2026-09-13 11:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinemas", "0002_cinematheme_accent_color_cinematheme_border_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was initially created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique public identifier for API lookups and routing.",
                        unique=True,
                        verbose_name="public UUID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Security action or event name (e.g. TENANT_REGISTERED, PROVISIONING_FAILED).",
                        max_length=100,
                        verbose_name="action",
                    ),
                ),
                (
                    "actor_email",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Email address of user or system agent initiating action.",
                        max_length=255,
                        verbose_name="actor email",
                    ),
                ),
                (
                    "tenant_slug",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Associated cinema tenant slug.",
                        max_length=63,
                        verbose_name="tenant slug",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Origin IP address for the audit record.",
                        null=True,
                        verbose_name="client IP address",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary structured metadata about this audit event.",
                        verbose_name="event metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Audit Log",
                "verbose_name_plural": "Platform Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="cinemadomain",
            name="cooldown_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Enforces 90-day quarantine before a released domain/subdomain can be re-registered.",
                null=True,
                verbose_name="cooldown quarantine expiration",
            ),
        ),
        migrations.AddField(
            model_name="cinemadomain",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("COOLING_DOWN", "Cooling Down"),
                    ("RELEASED", "Released"),
                ],
                db_index=True,
                default="ACTIVE",
                help_text="Current lifecycle status of this domain mapping.",
                max_length=20,
                verbose_name="domain status",
            ),
        ),
        migrations.AddField(
            model_name="cinematenant",
            name="last_provisioning_attempt_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent provisioning runner attempt.",
                null=True,
                verbose_name="last provisioning attempt at",
            ),
        ),
        migrations.AddField(
            model_name="cinematenant",
            name="provisioning_attempts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total number of provisioning execution attempts.",
                verbose_name="provisioning attempts",
            ),
        ),
        migrations.AddField(
            model_name="cinematenant",
            name="provisioning_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when schema provisioning and turnkey seeding finished.",
                null=True,
                verbose_name="provisioning completed at",
            ),
        ),
        migrations.AddField(
            model_name="cinematenant",
            name="provisioning_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Error diagnostic trace if provisioning failed.",
                verbose_name="provisioning error details",
            ),
        ),
        migrations.AddField(
            model_name="cinematenant",
            name="provisioning_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when async schema provisioning was started.",
                null=True,
                verbose_name="provisioning started at",
            ),
        ),
        migrations.AddField(
            model_name="cinematenant",
            name="provisioning_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROVISIONING", "Provisioning"),
                    ("READY", "Ready"),
                    ("FAILED", "Failed"),
                    ("RETRYING", "Retrying"),
                    ("SUSPENDED", "Suspended"),
                    ("DELETING", "Deleting"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Current lifecycle and provisioning state of the cinema tenant.",
                max_length=20,
                verbose_name="provisioning status",
            ),
        ),
        migrations.CreateModel(
            name="OnboardingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was initially created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique public identifier for API lookups and routing.",
                        unique=True,
                        verbose_name="public UUID",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text="Client-provided unique key from X-Idempotency-Key HTTP header.",
                        max_length=128,
                        unique=True,
                        verbose_name="idempotency key",
                    ),
                ),
                (
                    "request_hash",
                    models.CharField(
                        help_text="SHA-256 canonical hash of registration payload to detect payload mutation.",
                        max_length=64,
                        verbose_name="request payload hash",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("COMMITTED", "Committed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        max_length=20,
                        verbose_name="request status",
                    ),
                ),
                (
                    "response_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Exact response body returned to client for idempotent replay.",
                        verbose_name="cached response payload",
                    ),
                ),
                (
                    "response_status_code",
                    models.PositiveIntegerField(
                        default=202,
                        help_text="HTTP status code for idempotent replay (e.g. 202).",
                        verbose_name="cached response status code",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_requests",
                        to="cinemas.cinematenant",
                        verbose_name="cinema tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="operator user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Request",
                "verbose_name_plural": "Onboarding Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
