# Generated by Django 6.1 on 2026-09-13 11:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinemas", "0003_platformauditlog_cinemadomain_cooldown_until_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantOperationalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was initially created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last modified.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Globally unique public identifier for API lookups and routing.",
                        unique=True,
                        verbose_name="public UUID",
                    ),
                ),
                (
                    "hold_ttl_seconds",
                    models.PositiveIntegerField(
                        default=420,
                        help_text="Duration in seconds that selected seats are held during checkout (default: 420s / 7 mins).",
                        verbose_name="seat hold TTL (seconds)",
                    ),
                ),
                (
                    "max_seats_per_order",
                    models.PositiveIntegerField(
                        default=8,
                        help_text="Maximum number of seats bookable in a single order (default: 8).",
                        verbose_name="max seats per order",
                    ),
                ),
                (
                    "booking_confirmation_email",
                    models.BooleanField(
                        default=True,
                        help_text="Send automated email confirmation and QR tickets upon successful payment.",
                        verbose_name="email booking confirmations",
                    ),
                ),
                (
                    "booking_confirmation_sms",
                    models.BooleanField(
                        default=True,
                        help_text="Send automated SMS confirmation and short booking code upon payment.",
                        verbose_name="SMS booking confirmations",
                    ),
                ),
                (
                    "onboarding_checklist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Interactive launch checklist tracking setup milestones.",
                        verbose_name="onboarding checklist",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_config",
                        to="cinemas.cinematenant",
                        verbose_name="cinema tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Operational Configuration",
                "verbose_name_plural": "Tenant Operational Configurations",
            },
        ),
    ]
